create table
  public.submission (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    name text null,
    organization text null,
    links json null,
    topics json null,
    moderator boolean null default false,
    user_id text not null,
    type text null default 'default'::text,
    votes json null default '[]'::json,
    constraint applications_pkey primary key (id)
  ) tablespace pg_default;
